import Head from 'next/head';
import localFont from 'next/font/local';
import { useCalls } from '@/services/queries/useCalls';

const sfSans = localFont({
  src: [
    {
      path: '../styles/fonts/SFProDisplay-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../styles/fonts/SFProDisplay-Semibold.otf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-sf-sans',
  display: 'swap',
  preload: true,
});

export default function Home() {
  const { data, isLoading, isError } = useCalls({
    date_start: '2023-08-01',
    date_end: '2023-08-03',
    in_out: undefined,
    sort_by: 'date',
    order: 'DESC',
    limit: 20,
    offset: 0,
  });

  if (isLoading) return <div>Загрузка...</div>;
  if (isError) return <div>Ошибка загрузки</div>;

  return (
    <>
      <Head>
        <title>Skilla</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={` ${sfSans.variable}`}>я ебу собак</div>
    </>
  );
}
